# -----------------$HOME/.abcde.conf----------------- #
# 
#  A sample configuration file to convert music cds to 
#  MP3, Ogg Vorbis, FLAC, Musepack, AAC, WavPack, Opus,
#  Monkey's Audio (ape), True Audio, AC3 and mp2, 11 formats
#  at the same time! Using abcde version 2.7.2 release version.
# 
#   Acknowledgements to http://andrews-corner.org
# -------------------------------------------------- #

# ---------- Metadata ----------
CDDBMETHOD=musicbrainz
CDDISCID=mb-discid

# ---------- Ripping ----------
CDROMREADERSYNTAX=cdparanoia

# ---------- Encoders ----------
OGGENCODERSYNTAX=oggenc
MP3ENCODERSYNTAX=lame
FLACENCODERSYNTAX=flac
OPUSENCODERSYNTAX=opusenc

OGGENC=oggenc
LAME=lame
FLAC=flac
OPUSENC=opusenc

OGGENCOPTS='-q 8'
LAMEOPTS='-V 0'
FLACOPTS='-s -e -V -8'
OPUSENCOPTS='--vbr --bitrate 128'

# ---------- Output Formats ----------
OUTPUTTYPE="flac,opus,mp3,ogg"

# ---------- Actions ----------
ACTIONS=cddb,read,getalbumart,encode,tag,move,clean

# ---------- Output Location ----------
OUTPUTDIR="$HOME/Music"

# Standard albums
OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} ${TRACKFILE}'

# Various Artists albums
VAOUTPUTFORMAT='Various/${ALBUMFILE}/${TRACKNUM} ${ARTISTFILE} - ${TRACKFILE}'

# Single-track releases
ONETRACKOUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${ALBUMFILE}'
VAONETRACKOUTPUTFORMAT='Various/${ALBUMFILE}/${ALBUMFILE}'

# ---------- Filename cleanup ----------
mungefilename ()
{
  echo "$@" | sed -e 's/^\.*//' | tr -d ':><|*/"?[:cntrl:]'
}

# ---------- Misc ----------
LOWDISK=y
PADTRACKS=y
MAXPROCS=2
EXTRAVERBOSE=2
EJECTCD=y
