# -----------------$HOME/.abcde.conf----------------- #
# 
#  A sample configuration file to convert music cds to 
#  MP3, Ogg Vorbis, FLAC, Musepack, AAC, WavPack, Opus,
#  Monkey's Audio (ape), True Audio, AC3 and mp2, 11 formats
#  at the same time! Using abcde version 2.7.2 release version.
# 
#   Acknowledgements to http://andrews-corner.org
# -------------------------------------------------- #

LOWDISK=y
CDDBMETHOD=musicbrainz
CDDBCOPYLOCAL="y"
CDDBLOCALDIR="$HOME/.local/share/cddb"
CDDBLOCALRECURSIVE="y"
CDDBUSELOCAL="y"

OGGENCODERSYNTAX=oggenc
MP3ENCODERSYNTAX=lame
FLACENCODERSYNTAX=flac
OPUSENCODERSYNTAX=opusenc

OGGENC=oggenc
LAME=lame
FLAC=flac
OPUSENC=opusenc

OGGENCOPTS='-q 8'
LAMEOPTS='-V 0'
FLACOPTS='-s -e -V -8'
OPUSENCOPTS="--vbr --bitrate 128"

OUTPUTTYPE="ogg,mp3,flac,opus"

CDROMREADERSYNTAX=cdda2wav
CDDA2WAVOPTS="-paranoia 2"

CDDISCID=mb-discid
OUTPUTDIR="$HOME/Music"
ACTIONS=cddb,read,getalbumart,encode,tag,move,clean

OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} ${TRACKFILE}'
VAOUTPUTFORMAT='Various/${ALBUMFILE}/${TRACKNUM} ${TRACKFILE}-${TRACKFILE}'
ONETRACKOUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${ALBUMFILE}'
VAONETRACKOUTPUTFORMAT='Various/${ALBUMFILE}/${ALBUMFILE}'

mungefilename ()
{
  echo "$@" | sed -e 's/^\.*//' | tr -d ":><|*/\"'?[:cntrl:]"
}

MAXPROCS=2
PADTRACKS=y
EXTRAVERBOSE=2
EJECTCD=y
